a = set()

b=input("ENTER NUMBER:" )
a.add(int(b))
b=input("ENTER NUMBER:" )
a.add(int(b))
b=input("ENTER NUMBER:" )
a.add(int(b))
b=input("ENTER NUMBER:" )
a.add(int(b))
b=input("ENTER NUMBER:" )
a.add(int(b))
b=input("ENTER NUMBER:" )
a.add(int(b))
b=input("ENTER NUMBER:" )
a.add(int(b))

print(a)