# Print and then you know why I write \n and \"\".

a = "Asad is good boy\nHe score \"90%\" in final exam"

print(a)

#Most used escape sequence characters

# | Escape Sequence | Meaning         | Example                             |
# | --------------- | --------------- | ----------------------------------- |
# | `\n`            | New line        | `print("Hello\nWorld")`             |
# | `\t`            | Tab space       | `print("Hello\tWorld")`             |
# | `\\`            | Backslash       | `print("C:\\Users\\Asad")`          |
# | `\'`            | Single quote    | `print('It\'s good')`               |
# | `\"`            | Double quote    | `print("He said \"Hi\"")`           |
# | `\r`            | Carriage return | Cursor line start par aa jata hai   |
# | `\b`            | Backspace       | Previous character remove karta hai |
# | `\f`            | Form feed       | Page break jaisa effect             |
# | `\ooo`          | Octal value     | Character by octal number           |
# | `\xhh`          | Hex value       | Character by hex number             |
